services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      postgres_host: postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres: 
        condition: service_started