[project]
name = "manganova.api"
description = "MangaNova is an open-source project that provides manga information to users."
authors = [
    { name = "Gabriel Nobrega", email = "gabrieltkdnobrega63@gmail.com" },
]
dependencies = [
    "fastapi[standard]>=0.115.0",
    "pydantic>=2.9.2",
    "pydantic-settings>=2.5.2",
    "sqlalchemy[asyncio]>=2.0.35",
    "pyjwt>=2.9.0",
    "bcrypt>=4.2.0",
    "psycopg[binary]>=3.2.3",
    "aioboto3>=13.1.1",
    "python-magic>=0.4.27",
    "fluent-runtime>=0.4.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/MangaNova/manganova.api"

[project.optional-dependencies]
test = ["pytest>=8.3.3", "httpx>=0.27.2", "aiosqlite>=0.20.0"]
[tool.pdm]
distribution = false

[tool.pdm.scripts]
start.cmd = "uvicorn src.__main__:create_app --factory --host 0.0.0.0 --port 8000"
start.env_file = ".env"

dev.cmd = "uvicorn src.__main__:create_app --factory --reload-dir ./src --reload"
dev.env_file = ".env"

test.cmd = "pytest"

ruffCheck.cmd = "ruff check --fix"
ruffFormat.cmd = "ruff format"
mypyTypecheck.cmd = "mypy"

lint = { composite = ["ruffCheck", "ruffFormat", "mypyTypecheck"] }


[tool.pdm.dev-dependencies]
dev = [
    "commitizen>=3.29.0",
    "ruff>=0.6.7",
    "types-PyJWT>=1.7.1",
    "alembic>=1.13.3",
    "mypy>=1.11.2",
    "types-aioboto3>=13.1.1",
    "awscli-local[ver1]>=0.22.0",
]

[tool.mypy]
files = "src/**/*.py"

[tool.pyright]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "alembic",
    "typings",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
